name: Dash Main (remote initiator)

on:
  push:
  repository_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Start E2E
        if: github.event.action != 'end e2e'
        run: |
          curl -X POST https://api.github.com/repos/floreacosta/dash-automation/dispatches \
          -H "Accept: application/vnd.github+json" \
          -u ${{ secrets.ACCESS_TOKEN }} \
          -d '{"event_type": "start e2e", "client_payload": { "repository": "${{ github.repository }}" }}'

      - name: End E2E
        if: github.event.action == 'end e2e'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl -X POST https://api.github.com/repos/floreacosta/dash-automation/dispatches \
          -H "Accept: application/vnd.github+json" \
          -u ${{ secrets.ACCESS_TOKEN }} \
          -d '{"event_type": "ack", "client_payload": { "repository": "${{ github.repository }}" }}'

  say-goodbay:
    runs-on: ubuntu-latest
    needs: ['e2e']
    steps:
      - name: Should not run
        run: |
          echo "Should be canceled"