name: Dash Main (remote initiator)

on:
  push:
  repository_dispatch:
    types: ['start e2e', 'end e2e']

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Start E2E
        run: |
          curl -X POST https://api.github.com/repos/floreacosta/dash-automation/dispatches \
          -H "Accept: application/vnd.github+json" \
          -u ${{ secrets.ACCESS_TOKEN }} \
          -d '{"event_type": "start e2e", "client_payload": { "repository": "${{ github.repository }}" }}'

  say-goodbye-passed:
    runs-on: ubuntu-latest
    if: github.event.client_payload.passed == true
    steps:
      - name: E2E passed
        run: |
          echo "E2E passed"

  say-goodbye-failed:
    runs-on: ubuntu-latest
    if: github.event.client_payload.passed == false
    steps:
      - name: E2E failed
        run: |
          echo "E2E failed"